config/routes.rb
Rails.application.routes.draw do

  resources :challenges do
    resources :likes
  end

  resources :posts
  default_url_options :host => "localhost:3000"
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }
  
  
  root 'home#index'
  
  get 'home/dashboard'
  get 'home/my_sessions'
  get 'mychallenges', to: 'challenges#mychallenges'
  get 'users/index'





  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
class Challenge < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    validates :title, :activity, presence: true
    
    enum activity: [:Running, :Hiking, :Cycling, :Swimming, :Wheelchair,  :Moutain_Biking, :Snowboarding, :Skiing, :Walking, :Rowing, :Wakeboard]
    enum difficulty:[:Easy, :Medium, :Hard]

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :create, :show, :edit, :update, :destroy, :mychallenges]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all.order('difficulty ASC')
  end

  def mychallenges
    @challenges = Challenge.all
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)
    @challenge.user = current_user

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def challenge_params
      params.require(:challenge).permit(
        :title, 
        :number_of_day, 
        :activity, 
        :difficulty, 
        :distance, 
        :deadline, 
        :elevation,
        :trick,
        :duration
      )
      

    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%= form_with(model: challenge, local: true) do |form| %>
  <% if challenge.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(challenge.errors.count, "error") %> prohibited this post from being saved:</h5>
      <ul>
      <% @challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="d-flex justify-content-between flex-wrap">
    <div class="field col-sm-12 col-md-8 col-lg-8 col-xl-5 mb-3">
      <%= form.label :title %>
      <%= form.text_field :title, class:"w-100", placeholder:"Name your challenge"%>
      <p class="error text-danger mb-0"><%= @challenge.errors[:title][0] %></p>
      <p class="error text-danger mb-0"><%= @challenge.errors[:title][1] %></p>
    </div>
    <div class="field col-sm-12 col-lg-4 col-xl-4 mb-3">
      <%= form.label :activity %><br />
        <%=  form.collection_select :activity, Challenge.activities.map{ |a| [a.first,a.first] }, :first, :second %>
    </div>
    <div class="field col-sm-12 col-lg-4 col-xl-3 mb-3">
      <%= form.label :difficulty %><br />
      <%=  form.collection_select :difficulty, Challenge.difficulties.map{ |b| [b.first,b.first] },  :first, :second %>
    </div> 
    <div class="field col-sm-12 col-lg-4 col-xl-4 mb-3">
        <%= form.label "Number of days to do it" %>
        <%= form.text_field :deadline, placeholder:"Put a deadline in days" %>
    </div>
  </div>
  <hr>
  <div id="myAnswers" class="d-flex-custom justify-content-between flex-wrap">
    <div class="field col-sm-12 col-lg-4 col-xl-4 mb-3  Hiking Running Cycling Swimming Wheelchair Mountain_Biking Snowboarding Skiing Walking Rowing">
      <%= form.label :distance %>
      <%= form.text_field :distance, placeholder:"Put a distance in km" %>
    </div>
      <div class="field col-sm-12 col-md-4 mb-3  Hiking Running Cycling Swimming Wheelchair Mountain_Biking Snowboarding Skiing Walking Rowing">
        <%= form.label :duration %><br />
        <%= form.time_field :duration %>
      </div>
    <div class="field col-sm-12 col-lg-4 col-xl-4 mb-3  Hiking Running Cycling Swimming Wheelchair Mountain_Biking Snowboarding Skiing Walking Rowing">
      <%= form.label :elevation %>
      <%= form.text_field :elevation, placeholder:"Put an elevation in meter" %>
    </div>
    <div class="field col-sm-12 col-lg-4 col-xl-4 mb-3 fixtures Wakeboard Snowboarding Skiing Wheelchair">
      <%= form.label :trick %>
      <%= form.text_field :trick, placeholder:"Name trick to do" %>
    </div>
  </div>
    <hr>

  <div class="actions align-self-end col-sm-12 col-md-4">
    <%= form.submit :class=>"btn btn-primary f-trump btn-style" %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<header class="home-header">
    <div class="container py-5">
        <div class="card p-3 col-sm-12 col-md-10 col-lg-6 col-xl-6 mx-auto shadow">
            <h1>Editing Challenge</h1>

            <%= render 'form', challenge: @challenge %>
        </div>
        <div class="mt-3 col-sm-12 col-md-10 col-lg-6 col-xl-6 mx-auto">
            <%= link_to 'Show', @challenge %> |
            <%= link_to 'Back', challenges_path %>
         </div >
    </div>
</header>

app/views/challenges/index.html.erb
<header class="challenge-header bg-dark">
  <div class="container py-7">
    <h1 class="text-white">CHOOSE YOUR Challenge</h1>
      <label class="text-white mr-3">Select your activity</label>

      <select id="select-activity">
          <option value="Running">Running</option>
          <option value="Hiking">Hiking</option>
          <option value="Cycling">Cycling</option>
          <option value="Swimming">Swimming</option>
          <option value="Wheelchair">Wheelchair</option>
          <option value="Moutain_Biking">Moutain Biking</option>
          <option value="Snowboarding">Snowboarding</option>
          <option value="Skiing">Skiing</option>
          <option value="Walking">Walking</option>
          <option value="Rowing">Rowing</option>
          <option value="Wakeboard">Wakeboard</option>    
      </select>
 </div>
</header>

<section>
  <div class="container py-3 d-flex flex-wrap justify-content-start">
    <% @challenges.each do |challenge| %>
    <div class="col-sm-12 col-md-6 col-lg-4 myAnswers <%= challenge.activity %>">
      <div class="card p-3 shadow mb-3"
      <% if challenge.difficulty == "Hard"%> style="border:none; border-top:8px solid #FF2C2C"<% end %>
      <% if challenge.difficulty == "Medium"%> style="border:none; border-top:8px solid #D38013"<% end %>
      <% if challenge.difficulty == "Easy"%> style="border:none; border-top:8px solid #2C82FF"<% end %>
      >
        <div class="d-flex align-items-baseline">
          <%= render 'general/activity', obj:challenge %>
          <h4 class="ml-3"><%= challenge.activity %>: <%= challenge.title %></h4>
          <p class="ml-auto mr-0"><%= challenge.difficulty %></p>
        </div>
        <hr>
        <div class="d-flex justify-content-between">
          <% if challenge.distance.present?%>                        
            <div class="ml-3"><h4 class="mr-5 mb-0"><%= challenge.distance %> km</h4><p class="mb-0">Distance</p></div>
          <% end %>
          <% if challenge.elevation.present?%>
            <div><h4 class="mb-0"><%= challenge.elevation %></h4><p class="mb-0">Elevation</p></div>
          <% end %>
          <% if challenge.trick.present?%>
            <div><h6 class="mb-0 w-50"><%= challenge.trick %></h6><p class="mb-0">Trick</p></div>
          <% end %>
          <% if challenge.deadline.present?%>                        
            <div><h4 class="mr-5 mb-0"><%= pluralize(challenge.deadline, 'day') %></h4><p class="mb-0">Deadline</p></div>
          <% end %>
        </div>
        <hr>
        <% pre_like = challenge.likes.find { |like| like.user_id == current_user.id} %>
          <% if pre_like %>
            <%= link_to 'Unaccepted challenge', challenge_like_path(challenge, pre_like), method: :delete, :class=>"text-center mb-1" %>
            <%=image_tag("/assets/like-ok.svg", :class => "svg-like") %>
          <% else %>
            <%= link_to 'Accept challenge', challenge_likes_path(challenge), method: :post, :class=>"text-center mb-1" %>
            <%=image_tag("/assets/like.svg", :class => "svg-like") %>
        <% end %>
        <div class="d-flex justify-content-between align-items-center">
          <p class="mb-0"><%= challenge.likes.count %> <%= (challenge.likes.count) == 1 ? 'Like' : 'Likes'%></p>
          <div class="align-self-end ml-auto">
            <%if user_signed_in? && challenge.user == current_user%>
              <%= link_to 'Edit', edit_challenge_path(challenge) %> | 
              <%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</section>

app/views/challenges/mychallenges.html.erb
<header class="challenge-header bg-dark">
<div class="container py-7">
  <h1 class="text-white">CHOOSE YOUR Challenge</h1>
    <label class="text-white mr-3">Select your activity</label>

    <select id="select-activity">
        <option value="Running">Running</option>
        <option value="Hiking">Hiking</option>
        <option value="Cycling">Cycling</option>
        <option value="Swimming">Swimming</option>
        <option value="Wheelchair">Wheelchair</option>
        <option value="Moutain_Biking">Moutain Biking</option>
        <option value="Snowboarding">Snowboarding</option>
        <option value="Skiing">Skiing</option>
        <option value="Walking">Walking</option>
        <option value="Rowing">Rowing</option>
        <option value="Wakeboard">Wakeboard</option>    
    </select>
 </div>
</header>

<section>
  <div class="container py-3 d-flex flex-wrap justify-content-start">
    <% @challenges.each do |challenge| %>
    <% pre_like = challenge.likes.find { |like| like.user_id == current_user.id} %>
      <% if pre_like %>
        <div class="col-sm-12 col-md-6 col-lg-4 myAnswers <%= challenge.activity %>">
          <div class="card p-3 shadow mb-3"
          <% if challenge.difficulty == "Hard"%> style="border:none; border-top:8px solid #FF2C2C"<% end %>
            <% if challenge.difficulty == "Medium"%> style="border:none; border-top:8px solid #D38013"<% end %>
            <% if challenge.difficulty == "Easy"%> style="border:none; border-top:8px solid #2C82FF"<% end %>>
            <div class="d-flex align-items-baseline">
                  <%= render 'general/activity', obj:challenge %>
              <h4 class="ml-3"><%= challenge.activity %>: <%= challenge.title %></h4>
              <p class="ml-auto mr-0"><%= challenge.difficulty %></p>
            </div>
            <hr>
            <div class="d-flex justify-content-between">
              <% if challenge.distance.present?%>                        
              <div class="ml-3"><h4 class="mr-5 mb-0"><%= challenge.distance %> km</h4><p class="mb-0">Distance</p></div>
              <% end %>
              <% if challenge.elevation.present?%>
              <div><h4 class="mb-0"><%= challenge.elevation %></h4><p class="mb-0">Elevation</p></div>
              <% end %>
              <% if challenge.trick.present?%>
              <div><h6 class="mb-0 w-50"><%= challenge.trick %></h6><p class="mb-0">Trick</p></div>
              <% end %>
              <% if challenge.deadline.present?%>                        
              <div><h4 class="mr-5 mb-0"><%= pluralize(challenge.deadline, 'day') %></h4><p class="mb-0">Deadline</p></div>
              <% end %>
            </div>
            <hr>
            <% pre_like = challenge.likes.find { |like| like.user_id == current_user.id} %>
              <% if pre_like %>
                <%= link_to 'Unaccepted challenge', challenge_like_path(challenge, pre_like), method: :delete, :class=>"text-center mb-1" %>
                <%=image_tag("/assets/like-ok.svg", :class => "svg-like") %>
              <% else %>
                <%= link_to 'Accept challenge', challenge_likes_path(challenge), method: :post, :class=>"text-center mb-1" %>
                <%=image_tag("/assets/like.svg", :class => "svg-like") %>
            <% end %>
            <p><%= challenge.likes.count %> <%= (challenge.likes.count) == 1 ? 'Like' : 'Likes'%></p>
        </div>
  </div>
  <% end %>
  <% end %>
 
</section>

app/views/challenges/new.html.erb
<header class="home-header">
    <div class="container py-5">
        <div class="card p-3 col-sm-12 col-md-10 col-lg-6 col-xl-6 mx-auto shadow">
            <h1>New Challenge</h1>
            <%= render 'form', challenge: @challenge %>
        </div>
        <div class="mt-3 col-sm-12 col-md-10 col-lg-6 col-xl-6 mx-auto">
            <%= link_to 'Back', challenges_path %>
        </div >
    </div>
</header>

app/views/challenges/show.html.erb
 <header class="home-header">
  <div class="col-4 mx-auto py-7">
      <div class="card p-3 shadow mb-3"
        <% if @challenge.difficulty == "Hard"%> style="border:none; border-top:8px solid #FF2C2C"<% end %>
        <% if @challenge.difficulty == "Medium"%> style="border:none; border-top:8px solid #D38013"<% end %>
        <% if @challenge.difficulty == "Easy"%> style="border:none; border-top:8px solid #2C82FF"<% end %>>
        <div class="d-flex align-items-baseline">
          <%=image_tag("/assets/rowing.svg", :class => "svg-acivities") %>
          <h4 class="ml-3"><%= @challenge.title %></h4>
          <p class="ml-auto mr-0"><%= @challenge.difficulty %></p>
        </div>
        <hr>
        <div class="d-flex justify-content-between">
          <% if @challenge.distance.present?%>                        
            <div class="ml-3"><h4 class="mr-5 mb-0"><%= @challenge.distance %> km</h4><p class="mb-0">Distance</p></div>
          <% end %>
          <% if @challenge.elevation.present?%>
            <div><h4 class="mb-0"><%= @challenge.elevation %></h4><p class="mb-0">Elevation</p></div>
          <% end %>
          <% if @challenge.trick.present?%>
            <div><h6 class="mb-0 w-50"><%= @challenge.trick %></h6><p class="mb-0">Trick</p></div>
          <% end %>
          <% if @challenge.deadline.present?%>                        
            <div><h4 class="mr-5 mb-0"><%= pluralize(@challenge.deadline, 'day') %></h4><p class="mb-0">Deadline</p></div>
          <% end %>
        </div>
      </div>
      <div>
        <%= link_to 'Edit', edit_challenge_path(@challenge) %> |
        <%= link_to 'Back', challenges_path %>
      </div>
  </div>
</header>