config/routes.rb
Rails.application.routes.draw do

  resources :challenges do
    resources :likes
  end

  resources :posts
  default_url_options :host => "localhost:3000"
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }
  
  
  root 'home#index'
  
  get 'home/dashboard'
  get 'home/my_sessions'
  get 'mychallenges', to: 'challenges#mychallenges'
  get 'users/index'





  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white pt-6">
  <div class="container d-flex flex-wrap justify-content-around">
    <div class="col-sm-12 col-md-2 align-self-center">
      <ul class="text-right">
      <li><h4 class="text-primary">MOOVE AND GROOVE</h4></li>
      <li><%= link_to "Dashboard", home_dashboard_path, class:"text-white" %></li>
      <li><%= link_to "Challenge", challenges_path, class:"text-white" %></li>
      <li> <%= link_to "Add session", new_post_path, class:"text-white" %></li>
      <li><%= link_to "My sessions", home_my_sessions_path, class:"text-white" %></li>
      </ul>
    </div>
    <div class="col-sm-2 col-md-4 text-center">
          <a class="navbar-brand" href="#"><%=image_tag("/assets/logo-footer.png") %></a>
    </div>
    <div class="col-sm-12 col-md-2 align-self-center">
      <ul>
        <li><h4 class="text-primary">Social medias</h4></li>
        <li><a  class="text-white" href="#">Facebook</a></li>
        <li><a  class="text-white" href="#">Twitter</a></li>
        <li><a  class="text-white" href="#">Youtube</a></li>
        <li><a  class="text-white" href="#">Instagram</a></li>
      </ul>
    </div>
  </div>
  <div class="pt-6 pb-1 container">
  <hr>
    <p class="text-center">Made with 🤘 by <a class="text-white" target="_blank" href="https://www.linkedin.com/in/pierre-cammas/">Pierre CAMMAS</a></p>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand ml-sm-0 ml-md-5" href="http://localhost:3000"><%=image_tag("/assets/logo.svg") %></a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
    aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mr-5 align-items-baseline">
            <% if current_user %>
                <li class="nav-item">
                    <%= link_to "Dashboard", home_dashboard_path, class:"nav-link  text-white my-md-0 my-3" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white mr-3  mb-md-0 mb-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Challenges
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to "See challenges", challenges_path, class:"nav-link dropdown-item text-dark text-center" %>
                        <%= link_to "My challenges", mychallenges_path, class:"nav-link dropdown-item text-dark text-center" %>
                        <div class="dropdown-divider"></div>
                        <%= link_to "Add challenges", new_challenge_path, class:"nav-link dropdown-item text-dark text-center" %>
                    </div>
                </li>
                <li class="nav-item">
                    <%= link_to "add session", new_post_path, class:"btn btn-primary f-trump btn-style  mb-md-0 mb-3" %>
                </li>
        </ul>
    </div>
    <div class="dropleft nav-avatar">
        <% if current_user.photo.present?%>
            
            <%= link_to image_tag(current_user.photo.url(:thumb), :class => "avatar-picture"), "#", :id =>"dropdownMenuButton", :data => { :toggle => 'dropdown'} %>
        <% else %>
            <%= link_to image_tag(current_user.avatar, size:50, :class => "avatar-picture"), '#', :id =>"dropdownMenuButton", :data => { :toggle => 'dropdown'}%>
            
        <% end %>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <% if user_signed_in? %>
                <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, :class=>"dropdown-item" %>
                <%= link_to 'Edit profil', edit_user_registration_path, :class=>"dropdown-item" %>
            <%end%>
        </div>                      
    </div>
        <% else %>
            <li class="nav-item">
                <%= link_to 'SIGN UP', new_user_registration_path, :class => "btn btn-primary f-trump mr-4 btn-style"  %>
            </li>  
            <li class="nav-item">
                <%= link_to 'LOG IN', new_user_session_path, :class => "btn btn-white f-trump btn-style"  %>
            </li>
        </ul>
    </div>

            <% end %>
    
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mooveandgroove</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
      <%= render 'layouts/navigation'%>
      <% if notice.present?%>
      <div class="mb-0 alert-success fade show fade-out position-absolute card shadow" role="alert">
        <div class="card-header"><h5>Notification</h5></div>
        <div class="card-body bg-white"><%= notice %></div>
      </div>
      <% end %>
      <% if alert.present?%>
      <div class="mb-0 alert-warning fade show fade-out position-absolute card shadow" role="alert">
        <div class="card-header"><h5>Notification</h5></div>
        <div class="card-body bg-white"><%= alert %></div>      
      </div>
      <% end %>
      
    <%= yield %>

  <!-- <%= debug user_signed_in? %>
    <%= debug session.to_hash %> --> 

   <%= render 'layouts/footer'%>
   <%= javascript_pack_tag 'custom' %>
  </body>
</html>